# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29258fdf273a411d243ce1e1639621dc6204accd9ff336b348e8c2b2bbb8372718896bbc98aa8831b0631ccb200879a67b413ff6969e24baa35b3e68f04294b3

test:
  secret_key_base: 75236f25c0215eb35c6c4719c0087554bfbe297de38d668cc4e71da8ba1c6e08f2e6040fb06bdd2dbdf3f4aed71de34566ea3c4479387047cf7ac8cf746c7380

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
